export const RECEIVE_USER_ID = 'receive_user_id'
export const RECEIVE_USER_INFO = 'receive_user_info'
export const RECEIVE_PRODUCTS = 'receive_products'
export const RECEIVE_PRODUCTS_BY_QUERY = 'receive_products_by_query'
export const RECEIVE_PRODUCTS_BY_CATEGORY = 'receive_products_by_category'
export const RECEIVE_PRODUCT_CATEGORIES = 'receive_product_categories'
export const RECEIVE_SHOPPING_CARTS = 'receive_shopping_carts'
export const RECEIVE_ORDERS = 'receive_orders'
